name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
            - uses: actions/checkout@v2
            - name: Test Pacman
              run:
                echo Testing
                javac ../../src/*.java
                java ../../tests/TestConsume.java
                java ../../tests/TestAttack.java
                java ../../tests/TestMapEatCookie.java
