name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
            - uses: actions/checkout@v2
            - name: Test Pacman
              run: |
                echo Testing
                javac -cp "Projects/P3/src" Projects/P3/src/*.java
  testPacManConsume:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
          - uses: actions/checkout@v2
          - name: Compile and Run TestPacManConsume
            run: |
              cd Projects/P3/
              javac -cp "tests/*:src/:tests/" src/*.java tests/TestConsume.java
              java -cp "tests/*:src/:tests/" org.junit.runner.JUnitCore TestConsume
  testGhostAttack:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
          - uses: actions/checkout@v2
          - name: Compile and Run TestGhostAttack
            run: |
              cd Projects/P3/
              javac -cp "tests/*:src/:tests/" src/*.java tests/TestAttack.java
              java -cp "tests/*:src/:tests/" org.junit.runner.JUnitCore TestAttack
  testMapEatCookie:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
          - uses: actions/checkout@v2
          - name: Compile and Run TestMapEatCookie
            run: |
              cd Projects/P3/
              javac -cp "tests/*:src/:tests/" src/*.java tests/TestMapEatCookie.java
              java -cp "tests/*:src/:tests/" org.junit.runner.JUnitCore TestMapEatCookie
  testPacManMove:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
          - uses: actions/checkout@v2
          - name: Compile and Run TestPacManMove
            run: |
              cd Projects/P3/
              javac -cp "tests/*:src/:tests/" src/*.java tests/TestPacManMove.java
              java -cp "tests/*:src/:tests/" org.junit.runner.JUnitCore TestPacManMove
  testGhostMove:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
          - uses: actions/checkout@v2
          - name: Compile and Run TestGhostMove
            run: |
              cd Projects/P3/
              javac -cp "tests/*:src/:tests/" src/*.java tests/TestGhostMove.java
              java -cp "tests/*:src/:tests/" org.junit.runner.JUnitCore TestGhostMove
  testMapGetLoc:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
          - uses: actions/checkout@v2
          - name: Compile and Run TestMapGetLoc
            run: |
              cd Projects/P3/
              javac -cp "tests/*:src/:tests/" src/*.java tests/TestMapGetLoc.java                             
              java -cp "tests/*:src/:tests/" org.junit.runner.JUnitCore TestMapGetLoc
  
  testPacManValidMoves:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
          - uses: actions/checkout@v2
          - name: Compile and Run TestPacManValidMoves
            run: |
              cd Projects/P3/
              javac -cp "tests/*:src/:tests/" src/*.java tests/TestPacManValidMoves.java
              java -cp "tests/*:src/:tests/" org.junit.runner.JUnitCore TestPacManValidMoves
  testGhostValidMoves:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
          - uses: actions/checkout@v2
          - name: Compile and Run TestGhostValidMoves
            run: |
              cd Projects/P3/
              javac -cp "tests/*:src/:tests/" src/*.java tests/TestGhostValidMoves.java
              java -cp "tests/*:src/:tests/" org.junit.runner.JUnitCore TestGhostValidMoves
  testMapMove:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
          - uses: actions/checkout@v2
          - name: Compile and Run TestMapMove
            run: |
              cd Projects/P3/
              javac -cp "tests/*:src/:tests/" src/*.java tests/TestMapMove.java
              java -cp "tests/*:src/:tests/" org.junit.runner.JUnitCore TestMapMove
