name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
            - uses: actions/checkout@v2
            - name: Test Pacman
              run: |
                echo Testing
                javac -cp Projects/P3/src/*.java
  testPacManConsume:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
          - uses: actions/checkout@v2
          - name: Compile and Run TestPacManConsume
            run: |
              echo Testing
              javac -cp Projects/P3/src/*.java
              java -cp Projects/P3/tests/TestConsume.java
  testGhostAttack:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
          - uses: actions/checkout@v2
          - name: Compile and Run TestGhostAttack
            run: |
              echo Testing
              javac -cp Projects/P3/src/*.java
              java -cp Projects/P3/tests/TestAttack.java
  testMapEatCookie:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
          - uses: actions/checkout@v2
          - name: Compile and Run TestMapEatCookie
            run: |
              echo Testing
              javac -cp Projects/P3/src/*.java
              java -cp Projects/P3/tests/TestMapEatCookie.java
  testPacManMove:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
          - uses: actions/checkout@v2
          - name: Compile and Run TestPacManMove
            run: |
              echo Testing
              javac -cp Projects/P3/src/*.java
              java -cp Projects/P3/tests/TestPacManMove.java
  testGhostMove:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
          - uses: actions/checkout@v2
          - name: Compile and Run TestGhostMove
            run: |
              echo Testing
              javac -cp Projects/P3/src/*.java
              java -cp Projects/P3/tests/TestGhostMove.java
  testMapGetLoc:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
          - uses: actions/checkout@v2
          - name: Compile and Run TestMapGetLoc
            run: |
              echo Testing
              javac -cp Projects/P3/src/*.java                             
              java -cp Projects/P3/tests/TestMapGetLoc.java
  
  testPacManValidMoves:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
          - uses: actions/checkout@v2
          - name: Compile and Run TestPacManValidMoves
            run: |
              echo Testing
              javac -cp Projects/P3/src/*.java
              java -cp Projects/P3/tests/TestPacManValidMoves.java
  testGhostValidMoves:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
          - uses: actions/checkout@v2
          - name: Compile and Run TestGhostValidMoves
            run: |
              echo Testing
              javac -cp Projects/P3/src/*.java
              java -cp Projects/P3/tests/TestGhostValidMoves.java
  testMapMove:
      runs-on: ubuntu-latest
      container: openjdk
      steps:
          - uses: actions/checkout@v2
          - name: Compile and Run TestMapMove
            run: |
              echo Testing
              javac -cp Projects/P3/src/*.java
              java -cp Projects/P3/tests/TestMapMove.java
